### ISSUE TITLE
ChatBox

### ISSUE THREAD

**Issue by Maufa42** [0x1eef/0x1eef.github.io#1]
hi @0x1eef,
I'm Looking For Some Ideas that I can implement in OOD in Ruby and Found Yur Repo ( xchan.rb ) very Interesting . I'm on my 2nd Week of Learning Ruby, Followed by a Tremendous Amount Of Resources but am not able to clarify my thoughts while Designing Systems(Classes Based).

It Would be Great if you can Mentor Me for The Path Learning Ruby Or Suggest Some Resources.

Seeing Your Works 🤯Blows-Mind.

Looking To Here Form You

**Comment by 0x1eef** [comment]
Hey @Maufa42 

Sorry about the late reply. I haven't been checking my notifications.

I think that IRC can be a big help for talking through challenges you might run into, there's a lot of Ruby programmers who hang out there (including me) and I've always found them to be helpful and respectful. You can find me under the nickname `ox1eef` or `ox1eef_`. 

The network is `irc.libera.chat` and the channel is `#ruby`. I think the website https://libera.chat/ can help you get setup with IRC if you don't have experience with it yet. 

I can certainly try to help, but without knowing the particular challenges you are a facing that's a little hard to do. If you have particular questions, let me know and I will answer the best I can. 

Best regards,

**Comment by Maufa42** [comment]
I'm Piling up my Question and  will shoot my thoughts on this thread soon 
@0x1eef Thanks For The **IRC** advice.

**Comment by 0x1eef** [comment]
@Maufa42 

I saw your message on IRC. it usually requires hanging around a while, it can be a bit slow to get a response. I idle there all the time so I will see your messages sooner or later.

**Comment by Maufa42** [comment]
Great @0x1eef I will Send My Query there
